### ISSUE TITLE
How does this compare to proptest?

### ISSUE THREAD

**Issue by paldepind** [dubzzz/fast-check#108]
Hello. I just stumbled upon this library. It looks really nice :+1:

I've been using property-based testing with great success to find bugs in an [immutable list](https://github.com/funkia/list) implemented in TypeScript. It's really good to see a great looking TS implementation of property-based testing. The library I've been using is [proptest](https://github.com/danr/proptest). Would you happen to know how this library compares to Proptest?

One thing I really like about Proptest is the following (from the readme):

> Shrinking is done by generating lazy rose trees of values directly. This means that you can map and chain generators and get correct shrinking functions "for free". 

That is, the generators (which is what fast-check calls arbitraries) in Proptest are monads. It is possible to map them, chain them, and more. As far as I can see fast-check has a `map` function for its arbitraries but no monadic bind?

Additionally, Proptest has a nice integration with testing frameworks. See the [example here](https://github.com/danr/proptest#usage-with-mocha-and-jest). It makes it possible to declare tests in a really concise way. Have you considered adding something similar to fast-check?

Having to write `fc.assert(fc.property(...))` seems a bit cumbersome. Have you considered adding a function that is the composition of the two?

**Comment by dubzzz** [comment]
Hi,

Thanks a lot for the comments, I'll try to be as comprehensive as possible in my answer. Please do not hesitate to ask if you need more details or if something is unclear.

---

First of all I have not tried protest so far (will try to find some times to try it). I built fast-check because of limitations I encountered when playing around with jsverify (the top-starred JavaScript property based testing framework on GitHub for the moment).

Concerning shrinking, all arbitraries (except `lorem` with an issue opened on it) come with a shrinker. All the shrinking strategies derive from the three "root" arbitraries: `integer`, `array`, `tuple`.

Here are simplified implementations of some arbitraries provided by fast-check:
```
const ascii = fc.integer(0, 127).map(v => String.fromCodePoint(v));
const asciiString = fc.array(ascii).map(arr => arr.join(''));
const point = fc.tuple(fc.integer(), fc.integer()).map(d => ({x: d[0], y: d[1]});

// filter/map preserves shrinking capabilities 
```

Please let me know if you encounter problems on the shrink provided by fast-check.

---

Concerning the monadic aspect of arbitraries, a review and pull request is currently on its way to add such support. The current proposal is to use `then` and not `flatMap` as the shrink of such construct is not trivial at all.

Example to illustrate the difficulties of a real `flatMap`:

Let's say I generate a tuple of two positive integers `width` and `height`. And `flatMap` it into a 2d-array of integers. Now let's imagine the property fails whenever the matrix contains a -1.

It would look like:

```
fc.tuple(fc.nat(), fc.nat())
.flatMap(dims => {
 const [x, y] = dims;
 return fc.array(fc.integer(), x*y, x*y).map(arr => toGrid(arr, x, y));
```

Property based testing framework user, would want his framework to build a matrix of a single value -1. So shrink on width, height and content all together. Unfortunately if you shrink on width and height, your `flatMap` lost what was in the matrix. The function given to `flatMap` does not come with a shrinking manual. It cannot know that the issue was the -1, worst it does not know anything about the initial content.

In a nutshell, it might not shrink as well as other constructs. But the feature should be part of a next release.

---

No combination of `fc.assert` and `fc.property` for the moment. But I thought about it. 

Might be a great idea :) 

---

Features that you might benefit from using fast-check:
- replay on failure: basic features but unfortunately not all frameworks make it possible to restart directly on the failure case - most just take the seed and replay the whole sequence
- bias: some frameworks only generates small values in order to make classic counterexample more probable - others only build unbiased values and miss well known corner cases - others like fast-check produce more frequently small values on first runs and move to largers as the run ID increase
- pre conditions checks to discard runs with invalid entries - coming soon

Regards

**Comment by dubzzz** [comment]
Just to make it clearer. `map` automatically preserves shrinking, as `then` will.

So user does not have (except he really wants) to implement its own shrinker. Everything is done automatically.

Will be interested in having your feedback on fast-check.

Meanwhile, I will have a look to the projects you referenced in your last post

**Comment by paldepind** [comment]
Thanks a lot for your reply. You pretty much answered all my questions. I'll definitely be trying out fast-check when I get the time. I do have a few additional comments as well.

> The current proposal is to use `then` and not `flatMap` as the shrink of such construct is not trivial at all.

I understand the problem you described. But I'm not sure, does `then` solve the problem or is it just `flatMap` with a different name?

> No combination of fc.assert and fc.property for the moment. But I thought about it.

I think it would be really nice. I think it is great when the property based tests are as concise as possible as it makes them easier to read. [Here is an example](https://github.com/funkia/list/blob/master/test/index.ts#L420) of one my property based tests. The single function `check` collapses both the function call to `it`, `assert`, and `property`.

The code
```ts
it('foo', () => {
  fc.assert(fc.property(arb, prop));
});
```
Is essentially equivalent to
```ts
check('foo', arb, prop);
```

What do you think about that?

> replay on failure: basic features but unfortunately not all frameworks make it possible to restart directly on the failure case - most just take the seed and replay the whole sequence

That is a really nice feature :smile:

**Comment by dubzzz** [comment]
**flatMap**

> I understand the problem you described. But I'm not sure, does then solve the problem or is it just flatMap with a different name?

Indeed, it does not change the problem at all.

My problem with using `flatMap` was that most people will believe that it is a real monadic `flatMap`. Unfortunately, due to shrinking issue it is not as powerful as they would hope for a `flapMap`. Using another name was a solution to get rid off this ambiguouty. I even though of having an arbitrary for this #101.

As it is a very useful feature to draft quickly new arbitraries, it should definitely be part of the framework.

**combination of assert and property**

Just opened a ticket to follow this feature request: #109 

Your suggestion is pretty similar to the way it is handled in jsverify:
```js
describe("sort", function () {
  jsc.property("idempotent", "array nat", function (arr) {
    return _.isEqual(sort(sort(arr)), sort(arr));
  });
});
```

I am ok with the idea of wrapping `it`, `assert` and `property` all together to have a shorter way to run cheks. Nonetheless, I need to double check that `it` is ok across all main test frameworks used in JavaScript/TypeScript.

**other tips for fast-check**

I forgot another interesting feature I added to ease debugging when needed: verbose mode.

It basically prints all the failing cases encountered during the shrinking process. It can prove useful to visualize a common pattern among failing entries.

Some of those features are detailed in the documentation: https://github.com/dubzzz/fast-check#tips

*Please let me know if you encounter issues when trying fast-check. I would be glad to give you an hand if needed ;)*

**Comment by spion** [comment]
Just wanted to add I'm really excited about `flatMap`/`then` :grinning:

**Comment by dubzzz** [comment]
@paldepind 

**chain**

I just had a look into proptest (looked at the code and played with it). It indeed comes with a built-in `chain` method.

Unfortunately, it has the same problem as the one I decribed above concerning the poor shrinking of such chaining. In the case of this precise framework, a chained value is only shrunk on the last dimension - **the `chain` of fast-check shrinks on both dimensions.**

Moreover, this `chain` method is used to build `.array()` in proptest, so the impact of the poor shrinking is easily visible.

If you have a look into https://runkit.com/dubzzz/5b1bc7a8fd2901001208d045
You'll see that for the property:

> an array of natural numbers never contains a 8 (obviously false)

Counterexample for proptest: [8, 0, 0, 0, 0, 0, 0]
Counterexample for fast-check: [8]

**other remarks**

I think that the output of proptest could have been more verbose. For instance, it does not specify the seed that was used.

It also fails to generate large values by its own (certainly needs a manual intervention):

```js
// this one was always true in my case
property(
  'all natural numbers are inferior to 1000',
  QC.nat,
  x => x < 1000);
```

**Comment by dubzzz** [comment]
@spion We finally moved for `chain` instead of `flatMap` or `then`

**Comment by paldepind** [comment]
@dubzzz Thank you all your great comments! You've definitely convinced me of the benefits of fast-check. When I get the time I'll try an migrate to fast-check :smile:

**Comment by dubzzz** [comment]
@paldepind Please let me know if you need help during your migration. I can give you a hand ;)

**Comment by dubzzz** [comment]
@paldepind You might be interested: I started working on your idea to merge `assert`, `property` and `it` all together. The current proposal is described in #109.
