### ISSUE TITLE
Arbitrary set from array of constant values

### ISSUE THREAD

**Issue by benny-medflyt** [dubzzz/fast-check#127]
If I have:

```ts
const pizzaToppings: string[] = [
    "Pepperoni",
    "Mushrooms",
    "Onions",
    "Sausage",
    "Bacon",
    "Extra cheese",
    "Black olives",
    "Green peppers"
]
```

I would like to create an `Arbitrary<string[]>` that will deliver values such as:

```ts
const toppings1 = ["Pepperoni", "Onions", "Sausage"];
const toppings2 = ["Black olives"];
const toppings3 = [];
```

(The min and max size should be customizeable)
(Ideally the order in the results should be the same as the order in the `pizzaToppings` array)

I can use use `fc.set` but I believe this is not ideal because:
  - It is inefficient, it has to choose values and then prune out duplicates, instead of directly generating unique results (using unique array indices)
  - We may not have (or feel like writing) an appropriate comparison function, if the array elements are complex objects.

Thank you

**Comment by dubzzz** [comment]
Indeed the feature you suggest can be very useful and is not yet available out of the box.

The current way to do that would be `fc.set` or something more complex like:

```typescript
const toppings = [/*your data*/];
const topArb = fc.array(fc.boolean(), toppings.length, toppings.length)
  .map(selection => toppings.filter((v, id) => selection[id] === true));
```

Or maybe something based on `fc.genericTuple(..)` instead of `fc.array()`.

An implementation with min/max boundaries would require more work. In order to do that you can maybe use `fc.nat` with well selected boundaries instead of `fc.boolean`. And apply `filter` right after the `map` operation. The switch to `fc.nat` is just to limit the number of filtered values. 

The filter would be something like:
```typescript 
const boundTopArb = topArb.filter(ts => min <= ts.length && ts.length <= max);
```

---

Sent from my mobile, I have not tried to run the code above but it should work fine if no typos :)

**Comment by dubzzz** [comment]
For the naming I was thinking of something like: `fc.subarrayOf()` or `fc.subarrayFrom()`. I should also provide a shuffled version called `fc.shuffledSubarrayFrom/Of()`.

What do you think of those names? Any other suggestions?

**Comment by benny-medflyt** [comment]
Both of those names look good to me! :+1: 
For my use case I don't need the shuffled version, but looks like it could indeed come in handy sometime!
Thank you!

**Comment by dubzzz** [comment]
@benny-medflyt 

I just started to implement the `subarray` feature.
It should be part of the next release of fast-check - 1.5.0.
See PR #177.

Does it fit your needs?

**Comment by benny-medflyt** [comment]
Yeah that looks great thanks! This can be closed now

**Comment by dubzzz** [comment]
Great
