### ISSUE TITLE
jsonObject should not generate -0

### ISSUE THREAD

**Issue by david-golightly-leapyear** [dubzzz/fast-check#2030]
## 🐛 Bug Report

Values of `-0` are not valid in the JSON spec and should not be generated using `jsonObject`

## To Reproduce

Steps to reproduce:

`fc.jsonObject()`

Results: May yield a value of `-0`, which may cause a test failure if the code serializes and then deserializes the generated object:

```ts
  it('parses any valid JSON body', () => {
   fc.assert(
      fc.property(fc.jsonObject(), (payload) => {
        expect(JSON.parse(JSON.stringify(payload))).toEqual(payload) // fails if payload contains -0
      })
    )
  })
```

## Expected behavior

The value `-0` is not serializable as JSON, and therefore should not be generated using this generator.

See [RFC 8785](https://datatracker.ietf.org/doc/html/rfc8785#section-3.2.2.3), which references the [ES-262 spec](https://262.ecma-international.org/10.0/#sec-tostring-applied-to-the-number-type), which states (under `NumberToString`):

> If m is +0 or -0, return the String "0".

## Your environment

| Packages / Softwares  | Version(s) |
| --------------------- | ---------- |
| fast-check            |      2.17.0      |
| node                  |      12.14.1      |
| TypeScript*           |      4.3.2      |

*Only for TypeScript's users

**Comment by dubzzz** [comment]
Thanks a lot for the report.

According to [RFC-7159 - The JavaScript Object Notation](https://datatracker.ietf.org/doc/html/rfc7159#section-6), the following string is a valid JSON value: `{"a": -0}`. JavaScript is fully able to read it back. Meanwhile JavaScript totally fails the roundtrip whenever there is a `-0` (mostly because of `JSON.stringify`).

- `JSON.parse('{"a": -0}')`: preserves the -0
- `JSON.stringify({"a": -0})`: trims the -0

So actually in terms of json string it seems that -0 would be perfectly ok. But in the case of a 'json object' we might want to prevent -0 from popping because stringify badly handles it in JS 🤔

**Comment by dubzzz** [comment]
Here is a potential workaround for this issue:
```js
const myJsonObject = fc.jsonObject().map(v => JSON.parse(JSON.stringify(v)))
```

**Comment by dubzzz** [comment]
If `jsonObject` is supposed to represent any object that could have been retrieved by doing a `JSON.parse` on a random string then the current behaviour seems ok. But I'd definitely needs to make the documentation clearer regarding that point.

**Comment by dubzzz** [comment]
Closing the issue as it seems that everything has been done on documentation side to fully specify what to expect from the arbitrary. Please feel free to re-open the issue if you think there is something more to do or if the fix is not going in the right direction. I'd be happy to discuss about it if needed but for the moment it seems good.
