### ISSUE TITLE
adjacent subarray

### ISSUE THREAD

**Issue by codingedgar** [dubzzz/fast-check#2201]
## 🚀 Feature Request

An arbitrary like `subarray` but with adjacent (and sorted) values, or a flag in the existing `subarray`

## Motivation

This is quite useful for testing sets of values, and it's what I thought `subarray` actually did.
Is often necessary to test adjacent (most of the time sorted) values with anything related to arrays.

What I find myself doing often is creating the `array` then `chain` for the arguments for `slice` with `integer` and then `map` to an adjacent sorted subarray of the original array.

## Example

````
fc.subsequentsubarray([1, 42, 48, 69, 75, 92])
// Examples of generated values: [48,69,75,92], [75,92], [], [69], [1,42,48,69,75]…

// use case:
fc.array(fc.nat()).chain(fc.subsequentsubarray) // use the result to test unions/internections/etc
```

**Comment by dubzzz** [comment]
First, here is a possible implementation would be something like:

```js
function subsequentSubarray(arr) {
  return fc.tuple(fc.nat(arr.length),fc.nat(arr.length))
  .map(([a, b]) => a < b ? [a, b] : [b, a])
  .map(([from, to]) => arr.slice(from, to - from));
}
```
 _by relying on built-in map (instead of chain), we keep a powerful shrinker able to shrink 'most' of the problems_

Do you have examples of snippets where you had to use such construct? If the usage makes sense, one possibility would be to move everything onto subarray (even shuffled) to provide an unique entry point for subarrays in general.
