### ISSUE TITLE
Effectively integrating fast-check in a CI pipeline

### ISSUE THREAD

**Issue by kyythane** [dubzzz/fast-check#2278]
## 💬 Question and Help

Hello, apologies if I missed where this was mentioned in the documentation. I'm curious if there's a way to make fast-check runs deterministic for a given git hash and/or branch?  I'm concerned that fully non-deterministic runs would look like a flake when the test pipeline is retried.

**Comment by dubzzz** [comment]
Hello,

`assert` accepts a second argument that can declare the option `seed`. You can probably set it to something that fits your needs (a commit hash, a PR number...).

```ts
fc.assert(
  fc.property(...), 
  {seed: 42}
)
```

While it's possible to set it manually for each call to `assert`, fast-check offers a simple way to configure global configurations used by all assertions (except overriden locally): https://github.com/dubzzz/fast-check/blob/main/documentation/Tips.md#setup-global-settings

In general, I recommend not to hard-code the seed to a fixed constant even for CI runs. It tends to highly limit the benefits of pbt. At work or in fast-check itself the seeds have not been hard-coded, they are free to change for each new run. 

Hope it will help you 😅 Please let me know if you need more details.

**Comment by kyythane** [comment]
Hello, thank you for the quick response, and apologies for taking a while to respond back. 

If I set the `seed` option and have `numRuns` of 10, will it use the same seed for each of those runs?

**Comment by dubzzz** [comment]
Yes it will*, in reality the default behaviour is equivalent to set numRuns to 100. *But not regenerate the same values (generators is offset-ed).

**Comment by kyythane** [comment]
Ok, that's not quite what I want to do... taking a step back, really I want to make it so a failure is "sticky" until a test run with that `seed` and `path` passes. I guess I could build a wrapper for `fc.assert` that provides that sort of memory. It looks like I can get the necessary info using a `reporter`?

**Comment by dubzzz** [comment]
No sure to understand the exact need. Do you mean that instead of stopping when it finds a failure it should go ahead with it and continue until it reaches the 100 (or other) number of runs? If so assert ill not be enough, you should probably write a wrapper around property or give another predicate.

**Comment by kyythane** [comment]
Apologies for being unclear. I would like to log each failure case, and then build a mechanism to explicitly rerun those as part of the test pipeline for that branch until they pass (or are otherwise triaged in the case that a failure is flagged in a clearly unrelated PR).

**Comment by dubzzz** [comment]
For the logging part, you may want to check `{verbose: 1}` on `fc.assert`. It will log all the encountered failures and only them.

Regarding the replay, one possibility could be to use something like 'seed = PR number' or '= hash of branch name', so that your tests will always run against the same set of tests. Otherwise you could also use the `examples` flag on `fc.assert` (see https://github.com/dubzzz/fast-check/blob/main/documentation/Runners.md#runners).

Not sure it fully answers your need.
