### ISSUE TITLE
Allow to add example values directly to arbitraries

### ISSUE THREAD

**Issue by dbartholomae** [dubzzz/fast-check#2627]
## 🚀 Feature Request

I would love to have a way to add example values directly to arbitraries so they can be reused across multiple tests. These example values would need to be sampled before randomly generated values to ensure that they are actually sampled (at least if enough samples are drawn to cover the example range).

## Motivation and Example

Whenever I create a data type, I also create a related arbitrary so it can be used across tests, e. g.:

```ts
const userArb = record({
  name: string(),
  email: emailAddress(),
})
```

Let's say that my system reacts differently to specific test email addresses. Therefore I want to ensure that these email addresses are always part of tests so I don't accidentially handle introduce bugs. I could now, in each test, add the examples to the right place in the arbitrary used. But this is very very cumbersome and easy to forget.

Instead, I would love to just write something like:

```ts
const userArb = record({
  name: string(),
  email: examples(emailAddress(), "test@mycompany.org", "admin@mycompany.org"),
})
```

and then the examples arbitrary first returns all of the example values before generating new random values via `emailAddress()`.

Another benefit of this would be, that arbitraries could then be used to also create human-readable examples. This is helpful for tests which can't be written property-based, e. g. visual regression tests or stories for components in the frontend.

**Comment by dubzzz** [comment]
Hi @dbartholomae,

For the moment, I'd see possibly two way to achieve what you asked for:
- pass [examples][https://github.com/dubzzz/fast-check/blob/main/documentation/Tips.md#add-custom-examples-next-to-generated-ones) flag on `fc.assert` but it would be something to do per test
- use `oneof` to define your arbitrary: `fc.oneof(fc.emailAddress(), "test@mycompany.org", "admin@mycompany.org")`. By the way there is a way to force `oneof` to select it's first value by passing the prop `maxDepth:0` to it - [more details](https://github.com/dubzzz/fast-check/blob/main/documentation/Arbitraries.md#simple).

Here are some draft ideas that came to my mind when I tried to see how I could make fast-check evolve and include some kind of `example` if `oneof` does not fit:
- Other ways to implement that would somehow be to count the number of values that have been generated by the arbitrary. For the first one take the first example... but this approach would be broken by design as it will break the replay capabilities of fast-check.
- Based on the suggestion approach we may think about passing the runId to the arbitrary when we call it on generate. But how would we deal with things like `array(email())` on the 1st, 2nd runs?

**Comment by dbartholomae** [comment]
Thanks! The first suggestion would suffer from having to repeat the examples across tests.
The second is so far closest, with the main drawbacks being that a) this will create the fixed values way too often while maybe not generating enough different email addresses, and (less importantly) b) not guaranteeing using the example for the first time a value is generated, which prevents the additional use case I mentioned. With `frequency` instead of `oneOf` and a bit of tweaking of the frequencies, it might be good enough for now.
Also, I might misunderstand, but: Isn't `fc.oneof({ maxDepth: 0 }, fc.emailAddress(), "test@mycompany.org")` equivalent to `fc.emailAddress()`? If so, why would I ever use `maxDepth: 0` instead of just directly using the arbitrary?

For the solution, I had not thought about the replay. Without knowing all the context for the code base, I would assume that the easiest way to solve this problem would be to have a run counter available on the `Random` instance, but I'm not sure if the value of an `example` arbitrary is big enough to warrant such changes.

**Comment by dubzzz** [comment]
> Without knowing all the context for the code base, I would assume that the easiest way to solve this problem would be to have a run counter available on the Random instance, but I'm not sure if the value of an example arbitrary is big enough to warrant such changes.

During a replay `fast-check` can jump directly to any case without having to generate all the intermediate values. For instance, something like:

```ts
fc.assert(
  fc.property(fc.integer(), myPredicate),
  { seed: 1525890375951, path: '1000000' }
);
```

Would offset the arbitrary by `1000000` without having to generate any of the intermediate entries. Using a counter would force the need to regenerate all the intermediate entries.

> Also, I might misunderstand, but: Isn't fc.oneof({ maxDepth: 0 }, fc.emailAddress(), "test@mycompany.org") equivalent to fc.emailAddress()? If so, why would I ever use maxDepth: 0 instead of just directly using the arbitrary?

Regarding this one, I had no real production ready idea in mind. I was mostly thinking that by playing with maxDepth we could somehow makes something that generates always the passed defaults in some contexts. But it was clearly more a random idea than something fully working: I'll reiterate on it and keep you updated if I get something better with the maxDepth thing.
