### ISSUE TITLE
Generate TypeScript object Arbitraries

### ISSUE THREAD

**Issue by alialavia** [dubzzz/fast-check#265]
First, thanks for this magnificent library. I switched from jsVerify since couple of months ago and have already used fast-check for a couple of projects.

In my new company, we use TypeScript and I was wondering if there's any way we can get Arbitraries from TypeScript classes without manually writing them. Say I have a class like this:
```
class Blog {
   id: string,
   visited: Date
}

class Author {
   id: string,
   name: string,
   blogs: [Blog]
}
```

How can I generate samples for Author and Blog object without writing specific arbitraries for them, instead of, e.g. something like [this](https://github.com/dubzzz/fast-check/blob/master/example/binary-trees/arbitraries/PerfectBinaryTreeArbitrary.ts)

**Comment by dubzzz** [comment]
Hi,

For the moment no :'(

I actually have the very same need but have not found any ways to do that in TypeScript for the moment.
I would have wanted to provide something like: `fc.forType<MyInterface>()` able to generate the `Arbitrary` magically.

I looked into other projects that might have the same needs like https://github.com/gcanti/io-ts but they do not seem to provide such constructs. I also read stuff concerning transformers in TypeScript but it seems to be very difficult to use and add in the toolchain (even for the end-user).

So for the moment I still do not have anything for that.

Hoping to find a way to that soon ^^
Even some cli generating the `Arbitrary` code will do for my needs.

**Comment by alialavia** [comment]
Although AFAIK TypeScript doesn't have type reflections, I think there are ways around it. The fundamental question though is how to map TypeScript primary types to fast-check's. Should a number be mapped to an int arbitrary or a float arbitrary? And so on. At least, this the main problem IMO. What are other challenges involved?

**Comment by dubzzz** [comment]
Sorry for the late answer, IMO the question - How should we map a number? - is not the trickiest one - *maybe because introspection in ts afraid me more for the moment*. Basically we could force the user of the lib to specify its own default for all the primary types. In case all numbers are not integer or double we can give she/he the ability to override the default given path to the property or any other way to distinguish two properties.

I looked into ways to have introspection like for fast-check with TypeScript but it seems that it would require to use transformers (so ttsc, ttypescript) and also force users to do that in some way. Moreover it does not seem to be powerful enough for the needs of fast-check.

Example of transformers: https://github.com/kimamula/ts-transformer-keys

To be honest I have not found a simple way to solve all this challenge so far. I would really be interested into having a simple proof of concept to see how it could be done.

For the moment, the solutions I have would be:
- take a Swagger definition and build an Arbitrary from it
- take an instance and build another one from it - [code snippet](https://github.com/dubzzz/fuzz-rest-api/blob/master/test/inferPayloadArbitrary.js) - see issue #75

The advantage of those two solutions is that they both work for JavaScript users. The first one would be even more interesting has it would enable anyone having a Swagger to fuzz her/his APIs.

**Comment by dubzzz** [comment]
@alialavia I am closing the issue for the moment as I do not see any straighforward way to do that today. It is always part of my long term plan but I am waiting to see the future of transformers in TypeScript before moving on

**Comment by giogonzo** [comment]
Late to the party, but since `io-ts` has already been mentioned in this thread, here's a quick attempt at an `io-ts` Codec to `fast-check` Arbitrary generator: https://github.com/giogonzo/fast-check-io-ts
