### ISSUE TITLE
fast-check has no exported member named 'Command'

### ISSUE THREAD

**Issue by moodmosaic** [dubzzz/fast-check#2779]
## 💬 Question and Help

Getting this error when loading fast-check via Skypack in a Deno test suite:

*fast-check has no exported member named 'Command'*

```typescript
import * as fc
  from 'https://cdn.skypack.dev/fast-check';

class PushCommand implements fc.Command<Model, List> {
                                ^^^^^^^
  constructor(readonly value: number) { }

  check = (m: Readonly<Model>) =>
    true;

  run(m: Model, r: List): void {
    r.push(this.value); // impact the system
    ++m.num;            // impact the model
  }

  toString = () =>
    `push(${this.value})`;
}
```

Any help would be appreciated.

**Comment by moodmosaic** [comment]
Got it, have to run deno with `--no-check` option as in https://github.com/denoland/deno/issues/3321#issuecomment-695172229.

**Comment by moodmosaic** [comment]
@dubzzz I guess the alternative is to include those types in the .d.ts definitions? Or is there a way to trick the TypeScript compiler as-is?

**Comment by dubzzz** [comment]
It's quite surprising as I do export `Command` in the code 🤔 
See there: https://github.com/dubzzz/fast-check/blob/main/src/fast-check-default.ts#L322

**Comment by dubzzz** [comment]
And it appears in the generated and published typings https://cdn.jsdelivr.net/npm/fast-check@2.22.0/lib/types/fast-check-default.d.ts.

So it rather seem to be an issue on Skypack side? They probably ignore types published without any backing JS code (in other words pure types like this one).

**Comment by moodmosaic** [comment]
Just wondering, is Skypack the only way to use fast-check from deno?

**Comment by dubzzz** [comment]
Unfortunately, the only one I know of today. I just gave a try to something like **jsdelivr** but the main problem is that it would break because of dependencies not being referenced by an explicit url. In order to really support deno I should potentially do as I do for esm/cjs builds and add yet another build but it would imply some extra post-processing on the file generated by tsc.

Just opened a dedicated issue to track this need https://github.com/dubzzz/fast-check/issues/2781. No plan to work on it in the coming days but it would help me not to forget about it for the next features.
