### ISSUE TITLE
Simplify API

### ISSUE THREAD

**Issue by gunar** [dubzzz/fast-check#331]
The current API is expressive enough, but I believe it could be made more appealing to people new to PBT.

I suggest
1. Merging `fc.assert` and `fc.property` into `fc.test`.
2. Allowing primitive constructors as identifiers to built-in arbitraries.
3. Presenting `pre()` earlier on in the documentation.

 @dubzzz 	what do you think?

---

```diff
-const fc = require('fast-check');
+const { test } = require('fast-check');
 
 // Code under test
 const contains = (text, pattern) => text.indexOf(pattern) >= 0;
@@ -7,10 +7,10 @@
 describe('properties', () => {
   // string text always contains itself
   it('should always contain itself', () => {
-    fc.assert(fc.property(fc.string(), text => contains(text, text)));
+    test(String, text => contains(text, text));
   });
   // string a + b + c always contains b, whatever the values of a, b and c
   it('should always contain its substrings', () => {
-    fc.assert(fc.property(fc.string(), fc.string(), fc.string(), (a,b,c) => contains(a+b+c, b)));
+    test(String, String, String, (a,b,c) => contains(a+b+c, b));
   });
 });
```

**Comment by dubzzz** [comment]
Hi @gunar,

First of all thanks for the suggestions. Here are my feedbacks concerning those ones:

> Merging fc.assert and fc.property into fc.test

I believe the split between `assert` and `property` is the common way to go with property based testing.

One of the advantages is that you can easily change `fc.assert` into:
- `fc.check` -> not to throw
- `fc.sample` -> to see the generated values
- `fc.statistics` -> to analyze the look and feel of the generated values

I think the best thing would be to provide wrapper specific for each framework as I already did for https://github.com/dubzzz/ava-fast-check/ or am trying to do with https://github.com/facebook/jest/issues/8035

Here are some examples taken from different projects in different programming languages:

- scalacheck in Scala

```scala

  @Test
  def propertyDoNotHoldOnInfiniteStreams() {
    val inputGen = /* ... */
    check(Prop.forAll(inputGen) {gens: (List[Int], Int) => gens match {
      case (l, num) => LineRound.ofInt.merge_tiles(Stream.continually(l.toStream).flatten).take(num).size == num
    }})
}
```

`check` would be the equivalent of `fc.assert` and `Prop.forAll` the equivalent of `fc.property`.

- jsverify in JavaScript

```js
it(name, function () {
  jsc.assert(jsc.forall(...));
}
```

- testcheck in JavaScript

```js
check(
  property(
    gen.int, gen.int,
    (a, b) => a + b >= a && a + b >= b
  )
)
```

> Allowing primitive constructors as identifiers to built-in arbitraries

I am not really fond of using primitive `constructors` as shorthands for arbitraries:
- `String` is not shorter than `string`
- `String`: is it supposed to be a `fc.string()`, `fc.unicodeString()`...?
- `Number`: is it supposed to be an integer, a float, infinity?

Moreover it will highly complexify all the typings and require lots of changes to have it everywhere. Additionally there is no certainty that the users of fast-check building additional wrappers (wrappers similar to `array`, `tuple`...) will handle them as arbitraries.

> Presenting pre() earlier on in the documentation

Feel free to suggest the associated change in the documentation with a PR. So that we could discuus your suggestion together. The easier the documentation the better.

**Comment by dubzzz** [comment]
@gunar Any updates? Any feedbacks?

**Comment by gunar** [comment]
Not really, your answer pretty much nailed it. Thanks @dubzzz.
