### ISSUE TITLE
Clarify replay of fc.commands in documentation

### ISSUE THREAD

**Issue by BoruiGu** [dubzzz/fast-check#359]
In https://dubzzz.github.io/fast-check/#/1-Guides/Arbitraries it suggests fc.commands cannot be replayed

```
WARNING: fc.commands cannot be replayed for the moment
```

However in https://dubzzz.github.io/fast-check/#/1-Guides/Tips there's another note that commands can be replayed with `replayPath` (can we also add an example to show how to use `replayPath` to replay fc.commands?)

```
NOTE: Contrary to other arbitraries, commands built using fc.commands requires an extra parameter for replay purposes. In addition of passing { seed, path } to fc.assert, fc.commands must be called with { replayPath: string }.
```

**Comment by dubzzz** [comment]
@BoruiGu good catch: there was indeed a cleaning to do in the page https://dubzzz.github.io/fast-check/#/1-Guides/Arbitraries.

`fc.commands` are now fully replayable. The ability to replay them has been added in version 1.11.0: https://github.com/dubzzz/fast-check/blob/master/CHANGELOG.md#1110

I am adding a section in https://dubzzz.github.io/fast-check/#/1-Guides/Tips to explain how: see https://github.com/dubzzz/fast-check/pull/361

I let you close the issue if the documentation is clear enough after this update. Otherwise please let me know what should be added to make it clearer.
