### ISSUE TITLE
Implement quickspec based on fast-check

### ISSUE THREAD

**Issue by Dema** [dubzzz/fast-check#450]
## 💡 Idea

It would be great to have something similar to quickspec to be able to search for valid properties to test semi-automatically.

## Motivation

It's hard to come up with properties in a real-world scenarios. quickspec works similar to state machine model testing by combining functions and trying to find combinations that holds for all inputs

## Example

https://hackage.haskell.org/package/quickspec

**Comment by dubzzz** [comment]
Hi,

I had a look into quickspec yesterday evening. It's pretty amazing.

I don't think this kind of feature should be directly provided by fast-check.
**BUT** I drafted a quick implementation that seems to work pretty well so I might put it into another repo very soon so that you can try it in very early stage 😉

**Comment by dubzzz** [comment]
Here is the implementation I was talking about: https://www.npmjs.com/package/fast-spec
Or the GitHub repository: https://github.com/dubzzz/fast-spec

Beware of bugs, the code is really a quick-and-dirty implementation that does the job in a dummy way. There lots of features and enhancements to be added.
