### ISSUE TITLE
Additional arbitraries

### ISSUE THREAD

**Issue by tinydylan** [dubzzz/fast-check#477]
## 🚀 Feature Request

It would be convenient if the following Arbitrary instances were added to fast-check:

1. non-empty string
2. non-empty ascii string
3. non-empty array
4. positive integer
5. negative integer

## Motivation

While all of these can be created using the existing Arbitrary combinators, having these in the core fast-check would be a convenient short-cut.

JsVerify has nonempty string and nonempty array. Having these in fast-check would make migrating easier. 

## Example

Here is a real test in my project, TinyMCE:

```
UnitTest.test('Obj.size: inductive case', () => {
  fc.assert(fc.property(
    fc.dictionary(fc.asciiString(1, 30), fc.integer()),
    fc.asciiString(1, 30),
    fc.integer(),
    (obj, k, v) => {
      const objWithoutK = Obj.filter(obj, (x, i) => i !== k);
      Assert.eq('Adding key adds 1 to size',
        Obj.size(objWithoutK) + 1,
        Obj.size({ k: v, ...objWithoutK })
      );
    }));
});
```

With combinator 2 above, I could write:

```
UnitTest.test('Obj.size: inductive case', () => {
  fc.assert(fc.property(
    fc.dictionary(fc.nonEmptyAsciiString(), fc.integer()),
    fc.nonEmptyAsciiString(),
    fc.integer(),
    (obj, k, v) => {
      const objWithoutK = Obj.filter(obj, (x, i) => i !== k);
      Assert.eq('Adding key adds 1 to size',
        Obj.size(objWithoutK) + 1,
        Obj.size({ k: v, ...objWithoutK })
      );
    }));
});
```

If the feature is accepted, I'm happy to contribute the code.

**Comment by dubzzz** [comment]
@tinydylan I believe that the issue comes from the fact that whenever you want to specify a `min` length you also have to specify a `max`. There is an opened issue on this issue. The suggestion is to change the signature of all existing arbitraries (in a non breaking way by still supporting others) into something like `fc.string({min,max})` with `min` and `max` being optional values.

In my opinion, once we have the new way to pass parameters to arbitraries everywhere, building non-empty strings will not be painful anymore. The problem I have with adding new arbitraries to support the nonEmpty is that lots of arbitraries have this need and we might double the number of arbitraries 🤔

**Comment by tinydylan** [comment]
Agreed. Thanks!
