### ISSUE TITLE
High rate of duplicates when using fc.tuple

### ISSUE THREAD

**Issue by jonwhelan** [dubzzz/fast-check#524]
## 🐛 Bug Report

High rate of duplicate values are generated when using `fc.tuple`. 

## To Reproduce

```js
const fc = require('fast-check');


const cases = [
	[
		fc.emailAddress(),
		'using just `fc.emailAddress() results in no duplicates'
	],

	[
		fc.tuple(fc.integer(), fc.emailAddress()).map((arr) => arr[1]),
		'using tuple with a different type (e.g. `fc.integer()`) results in no duplicates'
	],

	// This is the case where behavior seems incorrect
	[
		fc.tuple(fc.emailAddress(), fc.emailAddress()).map((arr) => arr[1]),
		'using the same type in a tuple results in duplicates at a much higher rate than one would expect'
	]
];

cases.forEach(([arb, description]) => {
	console.log(`${description}:`);

	const seenEmails = {};

	fc.check(fc.property(arb, (emailAddress) => {
		if (seenEmails[emailAddress]) {
			console.log(`\t${emailAddress}`);
		}
		seenEmails[emailAddress] = true;
	}), {
		numRuns: 1000,
		seed: -1653245226 // should also be able to replicate without providing seed
	});
	console.log();
});

```

## Expected behavior

There should be no duplicates (or at least an extremely small chance of duplicates) in the 3rd case as demonstrated above.

## Your environment

| Packages / Softwares  | Version(s) |
| --------------------- | ---------- |
| fast-check            |      1.20.1      |
| node                  |       8.11.1     |

**Comment by dubzzz** [comment]
Thanks a lot for the report.

There is indeed something that looks pretty strange with `fc.tuple`. I'll need to spend a bit more time on it to understand what might be wrong with it  🤔

What's strange is the following:

- `fc.emailAddress()` - very few duplicates
- `fc.tuple(fc.emailAddress())` - very few duplicates on [0]
- `fc.tuple(fc.emailAddress(), fc.emailAddress())` - very few duplicates on [0]
- `fc.tuple(fc.emailAddress(), fc.emailAddress())` - **many duplicates on [1]**

Source: https://runkit.com/dubzzz/5e179d716ff70d001ae75e16

**Comment by dubzzz** [comment]
I think I have an idea of what can go wrong and create so many duplicates for the second member (and the next ones) of a tuple.

On code side everything looks fine at first glance, so I had to dig a bit more to get an idea. 

Before describing it, here are the observations I did during my investigation on https://runkit.com/dubzzz/5e184799286975001a101caf.
During my investigation I tried to restrict the issue to a smaller combination of arbitraries. So I replaced `webAddress` by a copy of its implementation and trimmed it step by step. But the behavior was strange: `tuple(array(subdomain(1,3)), array(subdomain(1,3)))` was fine, while `tuple(array(subdomain(1,4)), array(subdomain(1,4)))` was not. So I kept reducing my case to reach:  `subdomain` is `tuple(char(), string()).map(([a,b])=>a+b)` 🤔 (works for arrays having at most 3 items or less, fails for 4 and greater) 

Basically the problem seems to appear only when we ask fast-check to generate a very high number of values. 😳

Why can it be the case? 😵

Here is how fast-check works behind the scene:
1. When starting to run a property an instance of a random number generator is created based on the seed
2. In order to generate the values that will be used by the first execution a copy of this generator is done and used to generate the values. Let's say the generator is an object answering a number between 0 and 3 each time we call it. If we want to build one of (0,1,2), we call the generator, if value is 3 we discard it and ask for another one. Why not a modulo? Because it would led to an non uniform repartition of the generated values (50% of 0, 25% of 1, 25% of 2). So each time we have an issue with an unwanted value, we ask the generator a new one and offset it by one
3. We have or first value, let's build the next one. The one that will be used by our second execution
4. We take back the generator we had before (it has not been impacted when generating our first value as we cloned it). We offset it by a fixed number of generated values (see code of fast-check). Why not using the one used to generate the first value? We want to be able to regenerate intermediate values without having to regenerate all the values before. Why not a new generator based on another seed? Arfff, partly for legacy reasons. The original number generator used by fast-check was a mersenne twister. This kind of generator was expensive to build so offsetting it was better

So where is the issue?

Let's say we are building: `tuple(a, b)`
1. We build a generator, it has never been offset for the moment
2. a is used, it discarded 100 generated values and used 50 others
3. Generator offset is 150
4. b is used
5. Before generating our second value, we offset the generator (the original one) by 40 (why not?)
6. a is used, it discarded 60 and used 50
7. Generator offset is 150
8. 😣 b is used and will generate the exact same value as it has the 'same' generator

**Comment by dubzzz** [comment]
💥 By the way, there is another impact of the way fast-check generate values:

```js
// we build the values that would have been built if we were using fc.assert or fc.check
const [ dataRun1, dataRun2 ] = fc.sample(
    fc.array(fc.nat(2**32 - 3), 10000, 10000).noBias(),
    { numRuns: 2, seed: 1234 });
```

The content of `dataRun1` from index 42 to the end is the same as the one of `dataRun2` between index 0 to 9958 (not included).

In other words: `console.log(dataRun1.slice(42, 10000).join(',')` equals `dataRun2.slice(0, 9958).join(','))`.

**Comment by dubzzz** [comment]
From my recent analysis (following your bug report), the recommended way to generate multiple random subsequences using a prng is to implement a _jump_ method. It consists into offsetting the prng as if it was asked to generate a very huge amount of random numbers. In the case of xorshift128+ (default prng used by fast-check), the recommendation is to offset it by 2^64 😳 Hopefully there is a quick algorithm to do that efficiently. I'm working on adding the jump capability in pure-rand (lib uses by fast-check to generate its random values). _Too be continued..._

**Comment by jonwhelan** [comment]
Thanks for digging into this issue! Wish I could help out on a fix, but I just recently started using the library so still trying to grok the details of how the internals all fit together.

Is it correct to say that the root cause of the issue is that generators are being reused across arbitraries (because they are expensive to instantiate) and when reused we are offsetting them by a fixed amount, but if the previous arbitrary had to discard values greater than or equal to our offset then that's when we see duplicates?

**Comment by dubzzz** [comment]
The issue is now fixed on master. I will certainly release a new minor of fast-check soon to make those changes available.

The fix was to add the `jump` capability on the most important random number generators provided by pure-rand (whenever possible). `jump` is equivalent to ask the random number generator to skip thousands of generated values. It's a classical way to run independant computations based on random values. In the case of xorshift128+ - _the random number generator used by fast-check by default_ - the jump skips 2^64 values.

One of the consequences of this change is that the next minor will not generate the same values as the minor right before.
