### ISSUE TITLE
Lack of usage examples for Function arbitraries

### ISSUE THREAD

**Issue by mwgamble** [dubzzz/fast-check#531]
## 💬 Question and Help

It isn't really clear how to use the Function arbitraries such as `compareBooleanFunc`. It would be great if some usage examples could be added to the documentation to illustrate this.

**Comment by dubzzz** [comment]
Here is an example of how you may use `compareBooleanFunc`:

```js
test('should sort based on comparison function', () => {
  fc.assert(
    fc.property(
      fc.compareBooleanFunc(),
      fc.set(fc.nat()),
      (f, arr) => {
        const sortedArr = sort([...arr]);
        for (let i = 1 ; i < sortedArr.length ; ++i) 
          expect(f(sortedArr[i - 1], sortedArr[i])).toBe(true);
      }));
});
```

**Comment by dubzzz** [comment]
A code snippet using `compareBooleanFun` has been added into the set of examples available in fast-check: https://codesandbox.io/s/frosty-sammet-62urx?fontsize=14&hidenavigation=1&module=%2F001-simple%2Fsort%2Fmain.spec.ts&previewwindow=tests&theme=dark

**Comment by dubzzz** [comment]
@mwgamble Please feel free to re-open if it does not answer your question

**Comment by mwgamble** [comment]
@dubzzz I don't appear to have the ability to re-open the issue.

I'd never seen that codesandbox link before. Where is it linked from, other than this page? It definitely isn't obvious here:
https://dubzzz.github.io/fast-check/#/1-Guides/Arbitraries?id=functions
I'd also argue that directing someone to a test suite isn't a great form of documentation.

Additionally, `compareBooleanFunc` was only meant to be an example. My original post pointed out that there didn't appear to be any examples for any of the Function arbitraries, not just the `compareBooleanFunc` arbitrary.

Also these updates don't appear to have updated any of the docs at all (which is what was mentioned in my original post). The ideal situation would be worked examples of all arbitraries in the documentation. Right now, it isn't even clear why I'd want to use `compareBooleanFunc`, `compareFunc` (etc), including what situations they're most appropriate for.

**Comment by dubzzz** [comment]
*Where to find the link towards the codesandbox?*

The link towards the codesandbox is available on the [README](https://github.com/dubzzz/fast-check/blob/master/README.md) of the project which is also the page you can see on https://www.npmjs.com/package/fast-check.

![_20200130_074133~2](https://user-images.githubusercontent.com/5300235/73426351-59ab9980-4334-11ea-94fd-9aba0d3db0c6.JPG)

*Where to find code examples?*

There is a directory called `examples` at the root of the repository. It contains many code examples you can refer to when you need to. 

*Others*

Please note that as for any other open source project you are free to contribute if you believe you can come with a better option.

Here is the link to open pull requests:
https://github.com/dubzzz/fast-check/compare

And here are the contributions guidelines that you can obviously update if you think they do not provide enough details:
https://github.com/dubzzz/fast-check/blob/master/CONTRIBUTING.md

**Comment by mwgamble** [comment]
I'm not sure how I could contribute improvements to the documentation when I don't understand the concepts that need to be documented (which is the whole point of this issue - me requesting the relevant information).

**Comment by dubzzz** [comment]
*Ressources around property based testing*

If it can help, I recommend you take a look to the following ressources:

- The official getting started tutorial of fast-check - https://github.com/dubzzz/fast-check/blob/master/documentation/1-Guides/HandsOnPropertyBased.md
- The official set of examples - https://codesandbox.io/s/github/dubzzz/fast-check/tree/master/example?previewwindow=tests
- Full documentation - https://dubzzz.github.io/fast-check/#/
- An article I wrote to introduce people to property based testing - https://medium.com/criteo-labs/introduction-to-property-based-testing-f5236229d237
- And its follow up explaining how to find properties - https://medium.com/@nicolasdubien/find-the-best-properties-for-property-based-testing-ee2ed9d442e1

In addition here are other great materials you might want to check:
- By the creator of property based testing in general - https://www.youtube.com/watch?v=hXnS_Xjwk2Y
- Article on usages at Spotify - https://www.youtube.com/watch?v=hXnS_Xjwk2Y
- List of ressources around fast-check - https://github.com/dubzzz/awesome-fast-check/

*Doc issue*

If I understand well your point the main issue with the current doc is that for each *arbitrary* you'll be interested into having a code snippet right after or link towards a code snippet to show you how it might be used.

Well that's possible and it's more or less the reason why I added the codesandbox: showing examples people can play with, without having to setup anything on their own machine.

The reason why the codesandbox is limited to only a subset of the arbitraries is that, theoretically, using a function arbitrary should be the same as using an integer arbitrary: it's just that instead of asking the framework for integers you ask it for functions.

I'd be interested to know more about the pain points you have currently with the doc and how it can be fixed (suggestions of things that could have helped you).
