### ISSUE TITLE
log commands & stackoverflow

### ISSUE THREAD

**Issue by codingedgar** [dubzzz/fast-check#603]
## 💬 Question and Help

1. Is there a way to log the commands of Model Based Testing? or assert in general (for debugging purposes).

1. Is there a specific tag to do StackOverflow questions (I have a bunch of questions)

**Comment by dubzzz** [comment]
> 2. Is there a specific tag to do StackOverflow questions (I have a bunch of questions)

There is no specific tag on StackOverflow so far. Maybe just ask them here for the moment.

And you can maybe duplicate them on StackOverflow so that StackOverflow users will be able to find an answer for the issue if they encounter the same. (it can also make the project even more visible)

> 1. Is there a way to log the commands of Model Based Testing? or assert in general (for debugging purposes).

If you want to log something during the execution of a property you can add the generator called `fc.context`. Using it is briefly documented here https://github.com/dubzzz/fast-check/blob/master/documentation/1-Guides/Tips.md#log-within-a-predicate

You may also be interested by this part of the documentation https://github.com/dubzzz/fast-check/blob/master/documentation/1-Guides/Tips.md#replay-after-failure-for-commands. It explains how to replay failures encountered with `fc.commands`.

**Comment by codingedgar** [comment]
1. My thoughts exactly, I’ll do that.

1. `fc.context` Looks like exactly what I was looking for.

1. All of these leads me to another question: can I get the object that will printed when failed? Maybe throught `fc.context` or something similar? This is because I would like to have/build a cache system, so that the assert will try to reproduce failed scenarios in the next run (something similar to normal jest, retrying known failures before unknown ones), also maybe pickup where it left after a timeout. 

I’ve been using the method documented through copy paste, but it would be nice to automate it.

Not sure how non-invasive it would be, because I guess there’s no way to inject the “seed, etc” without explicitly adding something, (jest handles the cache/retry failures all behind curtain, without needing to add anything, but I don’t care at this point, just want to automate it first)

**Comment by dubzzz** [comment]
> try to reproduce failed scenarios in the next run

Actually there is a way to give fast-check some scenario, you always want to execute by specifying examples as explained here: https://github.com/dubzzz/fast-check/blob/master/documentation/1-Guides/Tips.md#add-custom-examples-next-to-generated-ones

But it is maybe what you meant by "**I’ve been using the method documented through copy paste, but it would be nice to automate it**".

If you want to avoid the copy-paste then you should move from `fc.assert` to `fc.check` and manually deal with the error reporting of failures. In its output `fc.check` comes with `counterexample` field (see [here](https://github.com/dubzzz/fast-check/blob/master/documentation/1-Guides/Runners.md#runners)).

> no way to inject the “seed, etc” without explicitly adding something

Actually there is one through the use of global settings: https://github.com/dubzzz/fast-check/blob/master/documentation/1-Guides/Tips.md#setup-global-settings

Something like `fc.configureGlobal({ seed: 10 });` will set the seed to be `10` in all the tests.

**Comment by codingedgar** [comment]
WOW!!! This library really has it all 💛

**Comment by codingedgar** [comment]
I tried to add the question to stack overflow, but don't have enough reputation yet to add a tag, if there's an existing tag I would copy those questions there.

**Comment by codingedgar** [comment]
Following the questions about Model Based Testing, I'm testing : http://todomvc.com/examples/react/#/ to get a sense of how it works, and I'm now in the "editing" commands, but I'm not sure how should I edit a random item.

I have a chain of commands like the following:
- Type valid todo
- Valid Enter (expecting to add a valid todo)
- Type valid todo
- Valid Enter (expecting to add a valid todo)
-> at this point, I have 2 todos.
- Edit todo (but which one?)

I'm not sure how to specify which _todo_ to edit, because I have no idea upfront how many would be.

Do you have an idea of what to do in these situations? how to "randomly but reproducible" choose one? only the state has knowledge of how many are, so making an arbitrary seems impossible.

I can think of three choices at this moment:
1. check there's more than 0, always pick the first one.
1. check there's more than 0, pick all available and edit them all.
1. do another test with a known number of todos.

It seems that with every step advanced the state gets more complicated, and the derivate states cannot be anticipated or chosen from arbitraries, am I wrong?

**Comment by dubzzz** [comment]
> Edit todo (but which one?)

In order to register your commands to `fast-check`, you use `fc.commands`. `fc.commands` takes as input an array containing producers of commands. Most of the time your producers will be `fc.constant(new MyCommand())` but you can use this feature to generate a command based on random data.

For instance in your case I'd do:
`fc.nat().map(seed => new EditTodo(seed))`

And whenever asked for a todo I'd select the todo at position `seed % number_of_todos`.

_Maybe better: I'd forbid `fc.nat()` to shrink as it will not provide much. To do that `fc.nat().noShrink().map(seed => new EditTodo(seed))`_

You maybe interested by this example: https://github.com/dubzzz/connect-four-react/tree/master/e2e/limited-model (see `ReopenViaUrlCommand`)

---

**_Given that, you may wonder: "Why don't you provide a generator of random generator?" So that users will be able to do `fc.rng().map(random => new MyCommand(random))`_**

IMO providing such generator natively in the farmework will make people use it everywhere and for things that might be done differently. `fc.rng()` would be impossible to shrink (at least I've never found ways to do that properly today) or at least provide a less powerful shrinker.

For that reason, while there are ways to do without it, I prefer not providing this arbitrary. Meanwhile it can be quite easily defined if needed.

**Comment by codingedgar** [comment]
thanks to https://github.com/dubzzz/fast-check/issues/598 leading to https://github.com/dubzzz/fast-check/pull/445 I think https://github.com/dubzzz/fast-check/issues/424 is related to my last question, generating scenarios to make a chain of scenarios is something I've been tinkering lately.

I guess one level nesting would be enough, I thought about: 

```ts
await fc.assert(
   fc.asyncProperty(...)
         ...
        async (x) => {
           await fc.assert(
             fc.asyncProperty(
               fc.commands([...]),
               async (commands) => {...}),
             {seed: sameAsParent}
```

But `scenario` seems similar.

I wanted to simplify the test by making one scenario without todos added, and another with todos, but the todos count and value should be also "random", that's why I got the idea to nest "properties".
