### ISSUE TITLE
Arbitraries for English language characters

### ISSUE THREAD

**Issue by tinydylan** [dubzzz/fast-check#642]
## 🚀 Feature Request

For my tests, I wish to make strings that only contain English language characters a-z, A-Z. I'd like variants with only uppercase, only lowercase, any case, and with or without numbers. All variants would have the min and max character count, and have both Character and String arbitraries.

Functions:

```
alpha()
upperAlpha()
lowerAlpha()
alphaNum()
upperAlphaNum()
lowerAlphaNum()

alphaString()
upperAlphaString()
lowerAlphaString()
alphaNumString()
upperAlphaNumString()
lowerAlphaNumString()
```

## Motivation

Lots of use cases involve strings with these characters. I often find myself using `hexaString` as an approximation.

## Example

This is a real test from TinyMCE - I'd like to use `fc.alphaNumString()` instead of `fc.hexaString()`. I could have used a full unicode set for the text - and that would have been a stronger test - but it introduces complexities such as encoding that aren't important for this particular test. However, expanding the character set from hex to alphaNum doesn't introduce any issues

```
  fc.assert(fc.property(htmlBlockTagName(), htmlInlineTagName(), fc.hexaString(), (block, inline, text) => {
    withShadowElement((ss) => {
      const id = 'theid';
      const inner = Element.fromHtml(`<${block}><p>hello<${inline} id="${id}">${text}</${inline}></p></${block}>`);
      Insert.append(ss, inner);

      const frog: Element<DomElement> = SelectorFind.descendant(ss, `#${id}`).getOrDie('Element not found');
      Assert.eq('textcontent', text, frog.dom().textContent);
    });
  }));
```

**Comment by tinydylan** [comment]
BTW - I'm happy to contribute the code.

**Comment by dubzzz** [comment]
While I clearly get the reason for such request, I'd prefer let users define their own custom arbitraries to deal with such cases. Actually, in my currrent vision, fast-check should provide the basic toolbox anyone can use to build their own tools. While some features may be border line, I'd say that the key is: if it is simple to build outside of fast-check let's keep it outside except if it adds lots of value.

For instance, if I chose to add alpha strings, I may be required to add number strings, emoji strings... While such helpers might be useful for some people I'd prefer put them outside of fast-check, so that the core only focuses on complex operations and let users come with their own arbitraries outside of fast-check. Moreover it can help to develop a larger ecosystem around fast-check.

`lowerAlpha` can be written as follow:
```js
const lowerAlphaString = (...args) => fc.stringOf(fc.constantFrom(...'abcdefghijklmnopqrstuvwxyz'), ...args)
const upperAlphaString = (...args) => lowerAlphaString(...args).map(s => s.toUpperCase())
const alphaString = (...args) => fc.mixedCase(lowerAlpha(...args))

// Or alternatively, mostly depending on how you want your shrinker to behave
const lowerAlphaString = (...args) => fc.stringOf(fc.nat(26).map(n => String.fromCharCode('a'.codePointAt(0) + n)), ...args)
```

**Comment by tinydylan** [comment]
I can understand your perspective here. I would have thought that some of these would be useful to all users, and common in similar tools. 

Are there any existing libraries of arbitraries that you recommend? I'd hate to repeat work someone else has done. Failing that, I'll spin up a library of arbitraries.

**Comment by dubzzz** [comment]
For the moment, I listed most of the libraries based on fast-check into https://github.com/dubzzz/awesome-fast-check

I believe the full list is the one on npm: https://www.npmjs.com/package/fast-check (see dependents tab)

**Comment by tinydylan** [comment]
Thanks. 

Closing this issue as you've marked it rejected.
