### ISSUE TITLE
It seams that there is no documentation of withBias

### ISSUE THREAD

**Issue by safareli** [dubzzz/fast-check#644]
It seams that there is no documentation of withBias would be great to have some, thanks!

**Comment by dubzzz** [comment]
There is a very small documentation on what is biased: https://github.com/dubzzz/fast-check/blob/master/documentation/1-Guides/AdvancedArbitraries.md#biased-arbitraries

**Comment by safareli** [comment]
So as I understand when you use let's say `fc.integer(0, 100)`  it's gonna generate numbers with equal distribution. but if you want to instead generate more smaller numbers instead of having equal distribution. you would do `fc.integer(0, 100).withBias(3)` which measns `1/3` ~ `33.33%` of the time you would get smaller values and 66.66% of the time you would get values from 0 to 100 with equal distribution. Which could also be done like this:

```js
fc.frequency(
  { weight: 1, arbitrary: fc.integer(0, 10 /*or some small number*/)},
  { weight: 2, arbitrary: fc.integer(0, 100)},
)
```

but useful part of withBies is that combinators propagate the `freq` so if you have
fc.array(fc.integer(0, 100),0,100).withBias(3) it will be equivalent of:

```js
fc.frequency(
  { weight: 1, arbitrary: fc.array(
    fc.frequency(
      { weight: 1, arbitrary: fc.integer(0, 10 /*or some small number*/)},
      { weight: 2, arbitrary: fc.integer(0, 100)},
    )
    , 0
    , 10 /*or some small number*/)
  },
  { weight: 2, arbitrary:fc.array(fc.integer(0, 100),0, 100)}
)
```

Is that correct?

**Comment by safareli** [comment]
Besides this I was looking at this tests:

https://github.com/dubzzz/fast-check/blob/master/test/e2e/arbitraries/Arbitrary.spec.ts#L6-L45

And trying to guess why this is working, can you also comment on that? Thanks!

**Comment by dubzzz** [comment]
Actually by default fast-check calls `withBias` on the passed arbitraries for you. The more tests it runs the less it asks for bias. If it was not the case, properties like the following ones wil never (or rarely fail):

```js
const failIfDuplicates = arr => new Set(arr).size === arr.length;

fc.assert(fc.property(
  fc.array(fc.nat()),
  arr => failIfDuplicates(arr)
))

// larger arrays generated by fast-check by default have a size of 10
// nat is between 0 and 2147483647
// the probability to generate twice the same value on such array is close to zero
```

```js
fc.assert(fc.property(
  fc.nat(), fc.nat(),
  (a, b) => a !== b
))

// nat is between 0 and 2147483647
// the probability to generate twice the same value is close to zero
// = 1 / 2147483648
```

_Remark: you can remove the ability to bias an arbitrary by calling `noBias()` on it_

In order to deal with such problem, some frameworks have different approaches but all of them have their own drawbacks. jsverify for instance only generates small integer values if you ask for arrays of intergers. As a consequence, the following property will always pass with jsverify:

```js
const jsc = require('jsverify')

jsc.assert(jsc.forall(
  jsc.nearray(jsc.nat),
  (arr) => arr[0] <= 1000
))
```

Others like RapidCheck in C++ increase the size of generated as you move in the runs. fast-check is closer from this one while it solves one of the issues that has this approach. Basically when you ask for arrays for natural numbers here is what you'll have with such approach:
- run 1/100: arrays having 0 to floor(10/100) items of values between 0 and 2147483647/100 = 21474836
- run 2/100: arrays having 0 to floor(2*10/100) items of values between 0 and 2*2147483647/100
...
- run 100/100: arrays having 0 to floor(100*10/100)=10 items of values between 0 and 100*2147483647/100 = 2147483647

While this approach seems pretty cool it has one major issue: how to deal with cases where the issues only appear on very small arrays with very large value? Something like `[2147483647]`.

In fast-check, the adopted approach is close to RapidCheck except that instead of always limiting the size, it let random select whether or not we should limit the size.

**Comment by dubzzz** [comment]
Let's take those tests one by one:

```ts
 it('Should bias nothing', () => { 
   const out = fc.check( 
     fc.property( 
       fc.nat().chain((c) => fc.tuple(fc.constant(c), fc.nat())), 
       (v: [number, number]) => !(v[0] > 100 && v[1] > 100) 
     ), 
     { seed: seed } 
   ); 
   expect(out.failed).toBe(true); 
 }); 
```

The property will only fail if `!(v[0] > 100 && v[1] > 100)` is false for one generated value of `v` which is equivalent to say `v[0] > 100 && v[1] > 100` is true.

As we expect a failure it means that we generated such `v` with `v[0] > 100 && v[1] > 100`. This one seems pretty legit as `nat` is supposed to generate values ranging from `0 to 2147483647`. Generating a value between `0` and `100` is rare... even more than rare if we consider equiprobable distributions.

```ts
 it('Should bias both source and destination', () => { 
   const out = fc.check( 
     fc.property( 
       fc.nat().chain((c) => fc.tuple(fc.constant(c), fc.nat())), 
       (v: [number, number]) => !(v[0] <= 100 && v[1] <= 100) 
     ), 
     { seed: seed } 
   ); 
   expect(out.failed).toBe(true); 
 }); 
```

We expect the property to fail, that is to say that (in 100 runs) fast-check was able to generate two values `v[0]` and `v[1]` such as `v[0] <= 100 && v[1] <= 100`.

Actually the probability of such event is null in the context of equiprobable distributions. Indeed, for a given run, the probability to generate `v[0]` between `0` and `100` is 0.0000046%. The probability to generate `v` such as `v[0] <= 100 && v[1] <= 100` is 0.00000000000022%. And this is where bias matter.

All other cases are basically variants of the same case. They are just there to check that we can have `v[0]` small when `v[1]` is large and the opposite too.

**Comment by dubzzz** [comment]
I clearly need to add more documentation on those topics. https://github.com/dubzzz/fast-check/issues/97 already asked for more documentation on shrinking, there is the exact same problem with bias.

**Comment by safareli** [comment]
Thanks for the explanation! I have created #653 to update the docs (feel free to reject it if you have better plans for updating documentation)

**Comment by dubzzz** [comment]
Full documentation on this topic will come soon

**Comment by dubzzz** [comment]
Documentation merged, see https://github.com/dubzzz/fast-check/blob/master/documentation/1-Guides/HowItWorks.md#bias

Please feel free to re-open
