### ISSUE TITLE
Question: Options for command generation

### ISSUE THREAD

**Issue by dgerrells** [dubzzz/fast-check#746]
Hiya,

I am trying to use the model based framework for UI integration automation via WebDriver. Idea is that we have a component on a page like a modal and then commands that a user can do on said component. This seems to be working well enough. 

Issue I am having is that many commands are predicated on a previous one completing. I can use the check method but this still misses most meaningful test paths. For example, at the start only valid option would be to open the modal, than there would be 3-4 more options after that etc. I know there was a new scenarios feature but I am not sure how that would work with this.

The key is I want an almost guarantee that a few specific cases get run without hitting timeouts since we are running end-to-end. I could drop out of this framework for those flows but I feel like this should already be doable with fast-check. I am a bit weak with functional programming so it could be that I am missing something trivial.

**Comment by dubzzz** [comment]
First, I'm really sorry for the delay. If I get it correctly: the issue is that some commands require very specific paths in order to be triggered. Thus not often executed.

Today, there is no way to tell the framework which path to take when generating the commands.

BUT there is a trick (only working for async properties) that may be ok for your need:
- Pass a large and custom maximal number of commands to `fc.commands`, like: `fc.commands(allCommands, 1000)`
- Set the option `interruptAfterTimeLimit` (time in milliseconds) on `fc.assert` - [more](https://github.com/dubzzz/fast-check/blob/master/documentation/1-Guides/Tips.md#avoid-tests-to-reach-the-timeout-of-your-test-runner)
- (no built-in in fast-check for this one) If you want to cut, the current run at the middle you can just skip all the non-executed commands by doing a `return false` in the `check` method of all your commands

With point 1. and 2. enabled, fast-check will generate longer sequences of commands, thus there is an higher probability to fall in the case you were talking about. Thanks to 2., the runner of fast-check will not start any additional runs as soon as the timeout gets reached. With 3. you can make your commands stop to execute if they take too long for a single run (there is also a `timeout` option on `assert` but it would mark the run as failed if it exceeds the time limit, there is nothing to stop a run at the middle today).

Regarding 3., you may have something like that:
```ts
const StopAfterTimeMs = 1000;

class PushCommand implements fc.AsyncCommand<Model, List> {
  // other methods...
  check = (m: Readonly<Model>) => {
    if (Date.now() - m.startTime > StopAfterTimeMs) {
      // Remark: While this work-around should work fine
      // You have to make sure that as soon as one run expired, no other runs will be started
      // (ensured by the fact that here we expire if current run takes more than StopAfterTimeMs)
      // (global execution will stop if some of runs takes more than StopAfterTimeMs, see interruptAfterTimeLimit)
      // If it is not the case, replay might not work correctly anymore!
      return false;
    }
    // your usual checks
  }
}

// later in the code
await fc.assert(
  fc.asyncProperty(fc.commands(allCommands, 1000), async cmds => {
    const s = () => ({ model: { startTime: Date.now(), /* stuff */ }, real: { /* stuff */ } });
    await fc.asyncModelRun(s, cmds);
  }), { interruptAfterTimeLimit: StopAfterTimeMs }
);
```
