### ISSUE TITLE
Add fast-check examples to shrinking challenge

### ISSUE THREAD

**Issue by jlink** [dubzzz/fast-check#899]
## 💡 Idea

There’s a repository targeted at comparing shrinking behaviour of various PBT libraries: https://github.com/jlink/shrinking-challenge

Would be great to have scalacheck therein. We’re happy to take PRs.

## Motivation

Shrinking behaviour is crucial to effective PBT and a large differentiator for choosing  the right one.  Adding to the challenge can be both a showcase and a motivator for improving fast-check‘s shrinking capabilities.

**Comment by dubzzz** [comment]
Good idea 💡

**Comment by jlink** [comment]
Feel free to ask for support.

**Comment by dubzzz** [comment]
@jlink I start to re-implement most of the challenges for fast-check. Here is my current commit https://github.com/dubzzz/shrinking-challenge/commit/2630c12a681c61cb75ca844c90ea4568435eab64 to add most of them.

The challenges you cover are pretty interesting. In some of them I can see that fast-check struggles to shrink in others that it struggles to even find the bug (with the default 100 runs). I will dig a little bit into some of the edge cases it found, they will be pretty useful materials for next iterations and changes over fast-check.

**Comment by dubzzz** [comment]
Here are some things I discovered when building fast-check:

---

In some frameworks, when you ask for an `Array(Int)` you get arrays containing only small values for integers.
_eg.: jsverify does that in JavaScript_

The workaround is to manually specify the range for the integers with something like `Array(Int(-2**31,2**31-1))` but in that case the framework will not be able to generate arrays with duplicated values (no more collisions).

In others, in an attempt to fix that problem they consider that first runs should only generate small values while later one will only generate large ones. In other words for first runs you get `SmallArray(Int(-31,32))` and for large ones `LargeArray(Int(-2**31,2**31-1))`.
_eg.: RapidCheck does that in C++_

Problem: It'll be difficult to have large arrays containing only small values.

---

You may refer to that section in the documentation of fast-check https://github.com/dubzzz/fast-check/blob/master/documentation/HowItWorks.md#bias

**Comment by jlink** [comment]
@dubzzz Feel free to open a PR whenever you feel ready. Nothing is perfect, don't wait for it ;-)

And I do think that the most valuable part of the challenge is the motivation to improve a PBT library.

**Comment by dubzzz** [comment]
@jlink I do not forget this issue. I'm working on a new (minor) release of fast-check that should include more efficient shrinkers. I should come back to you as soon as my new version is ready so that I can add some results onto the repo.

**When you say:**
> Over 100 runs, Hypothesis performed between 109 and 253 evaluations during shrinking

_See https://github.com/jlink/shrinking-challenge/blob/main/pbt-libraries/hypothesis/challenges/bound5.md_

Are we ok that it corresponds to the number of calls to the check method once we found the first issue?

**When you say "Over 100 runs"**, do you have a script to regenerate the report or was it one shot?

**As the challenge is about shrink and not edge case detection**, do you artificially increase the number of runs to increase the chance to find an issue? I'm asking that because by default fast-check uses the full integer range (2**53 values) when asked for integers (while some pbt libraries default the range of integers to very small ones).

**Comment by jlink** [comment]
@dubzzz For jqwik I use the Python script from hypothesis to compute the statistics: https://github.com/jlink/shrinking-challenge/blob/main/pbt-libraries/hypothesis/support/make_report.py
I later change the text of the generated reports by hand. This could definitely be improved. And yes, your assumption about the # of calls after the first detected failing sample is correct. 

As for jqwik I do not increase the number of runs but rely on jqwik‘s built in edge cases generation mechanism. In the current challenges that suffices to detect a first failing example almost always. The default is 1000 tries, which I think is already quite high.

**Comment by dubzzz** [comment]
Perfect 👌 Thanks a lot for the answers

**Comment by dubzzz** [comment]
Coming soon!

I'll release my next minor this evening and I hope to be able to open a PR with some first runs pretty soon.

By the way, thanks a lot for this repository. It is pretty cool to be able to compare the strengths and weaknesses of each solution so that we can work on enhancing all of them.

**Comment by dubzzz** [comment]
Closing the issue on fast-check side as the PR has been opened
