### ISSUE TITLE
TypedArray Arbitraries?

### ISSUE THREAD

**Issue by bitjson** [dubzzz/fast-check#96]
Fantastic work on this library! I’ve been hoping to find a good excuse to try it on a real project for a while now.

What’s the cleanest/fastest way to generate varying lengths of random TypedArrays?

One feature that would be really helpful might be some concise, built-in arbitraries for generating TypedArrays (or even just some as-efficient-as possible examples in the readme).

**Comment by dubzzz** [comment]
Hello @bitjson ,

In order to generate _varying lengths of random TypedArray_ you can use one of the `fc.array` signature.

The one to choose depends on the data you want to generate:

- you don't have any constraints on the length: you can use either (1) `fc.array(yourTypeArbitrary)` or (2) `fc.array(yourTypeArbitrary, maxSize: number)`. Signature (1) builds arrays of size between 0 and 10 (inclusive) in order to avoid having too large entries and causing them to run too long. Signature (2) can be used if you are ok to run your code on longer entries
- you want arrays with a maximal length of `maxLength`: you can use `fc.array(yourTypeArbitrary, maxSize: number)`
- you want arrays with a minimal size of `minLength`: `fc.array(yourTypeArbitrary, minSize: number, maxSize: number)`. Current signature forces the user to specify a maximal length too. The problem should be overcome by https://github.com/dubzzz/fast-check/issues/89 but I am still not sure on the way I will handle it

As an example, let's say you want to test a `sort` algorithm, you may generate arrays of integers using `fc.array(fc.integer())` that way:

```js
import * as assert from 'assert';
import * as fc from 'fast-check';
import { stableSort } from './implem';

describe('stable sort', () => {
  it('should produce an ordered array', () =>
    fc.assert(
      fc.property(fc.array(fc.integer()), data => {
        const sorted = stableSort(data, (a, b) => a - b);
        for (let idx = 1; idx < sorted.length; ++idx) {
          assert.ok(sorted[idx - 1] <= sorted[idx]);
        }
      })
    ));
});
```

More on the sort algorithm with fast-check at https://github.com/dubzzz/fast-check-examples/tree/master/test/stable%20sort

I might need to add something on it on the documentation ;)
Does it answers your needs?

**Comment by bitjson** [comment]
Thanks for the quick and thorough response! Sorry, I should have linked before – I'm thinking about arbitraries for ES2015 [TypedArray Views](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Typed_arrays).

Right now I'm just `.map`ing `fc.array`s onto a function the creates a new TypedArray from the array, e.g. `new Uint8Array(array)`, but under the covers, that's much less efficient than creating an arbitrary "from scratch" that avoids creating a normal Array first. (And a bit less ergonomic when testing lots of methods with TypedArrays).

Would you be open to a PR which adds arbitraries for TypedArray views?

**Comment by dubzzz** [comment]
For the moment, I do not manage them in fast-check. I need to add them for next releases.

The easiest way to build them is:

```js
// JavaScript snippet: aLen, bLen are optional number parameters
const int8array = (aLen, bLen) => fc.array(fc.integer(-128, 127), aLen, bLen).map(a => Int8Array.from(a));
const uint8array = (aLen, bLen) => fc.array(fc.integer(0, 255), aLen, bLen).map(a => Uint8Array.from(a));
const int16array = (aLen, bLen) => fc.array(fc.integer(-32768, 32767), aLen, bLen).map(a => Int16Array.from(a));
const uint16array = (aLen, bLen) => fc.array(fc.integer(0, 65535), aLen, bLen).map(a => Uint16Array.from(a));
const int32array = (aLen, bLen) => fc.array(fc.integer(), aLen, bLen).map(a => Int32Array.from(a));
const uint32array = (aLen, bLen) => fc.array(fc.integer(), aLen, bLen).map(a => Int32Array.from(a), x => x + 2147483648);
```

You can extract the first ten generated values using:

```js
fc.sample(int8array(), 10); // int8 arrays
fc.sample(int8array(2), 10); // int8 arrays of maximal size 2
fc.sample(int8array(2, 5), 10); // int8 arrays of size between 2 and 5
```

**Comment by dubzzz** [comment]
I am totally opened for a PR adding TypedArray :)
Please let me know if you want to do it, or I can handle it too

**Comment by bitjson** [comment]
Nice, thanks for the snippets!

I'd love to dig in and try it myself – I'm about to go offline for the next week though, so not sure if I'd be able to get ramped up and send it before I leave.

What do you think the API should look like? Similar to `fc.array`?

**Comment by bitjson** [comment]
I started to duplicate `ArrayArbitrary.ts` and work it into a `TypedArrayArbitrary.ts`:

```
class TypedArrayArbitrary<T> extends Arbitrary<T[]> {
  readonly lengthArb: ArbitraryWithShrink<number>;
  constructor(
    readonly minLength: number,
    readonly maxLength: number,
    readonly arb: IntegerArbitrary,
    readonly preFilter: (tab: Shrinkable<T>[]) => Shrinkable<T>[] = tab => tab
  ) {
    super();
    this.lengthArb = integer(minLength, maxLength);
  }
```

But I don't think I grok how shrinking or biases work yet, so I'm afraid I won't have time to finish an implementation.

Please don't let me hold you up if you have a solid idea of how you'd like it implemented!

(And if it's not done yet in a couple weeks, maybe I can try my hand when I get back. 😄)

**Comment by dubzzz** [comment]
On my side, I would suggest an API like the one provided by `fc.array`.
Just to be compliant with the current arbitraries.

Concerning the extended API - *the one with a third parameter being an `Arbitrary<number>`* - I might go for something else.
The problem I see with taking an Arbitrary as a third parameter is that you cannot be sure the range of values produced by your Arbitrary is within the `uint8`. I would have moved for:

```typescript
interface ConstrainedValue {
  min?: number;
  max?: number;
}
fc.uint8Array(minLength?: number, maxLength?: number, constraints?: ConstrainedValue);
```

It will allow to run constraints checks on `uint8Array` creation. But I am totally opened to suggestions on this part.

**Comment by dubzzz** [comment]
Concerning **shrink** and **biased** I will update the documentation and add a section to give a better understanding of those choices.

# Shrink and Biased in few words

## Shrink

Some property based testing framework chose the following structure for `Arbitrary`:

```typescript
interface ArbitraryV0<T> {
  generate(mrng: Random): T;
  shrink(value: T): Stream<T>;
}
```

It is for instance the case of `jsverify` and was the case of the pre-v0.0.1 version of `fast-check`.

While this approach seems perfect it has many issues. For instance you cannot shrink something produced by a `oneof` because as soon as the `generate` method returns you have lost all the data concerning the arbitrary that generated the value so you cannot shrink anymore.

For that reason the interface of `Arbitrary` of `fast-check` only provides a `generate` method. The shrinking part is handled by a `Shrinkable` structure which holds all the data required to generate smaller entries.

## Biased

Providing biased version of an `Arbitrary` is not compulsary but recommended whenever possible.

Another recurrent problem with property based testing frameworks is that they either generate too large entries or two small so that you do not encounter the corner cases. The classical way to get rid off this problem is to tweak the arbitraries manually to have small arrays, large arrays, small values...

For instance let's say you want to test an algorithm able to remove duplicates from an array of integers. If you build the array using `fc.array(fc.integer())` you tell the framework that integers can take any 32 bits values. An unbiased version of the `Arbitrary` will produce very few entries having duplicates. For this reason `fast-check@1.1.0` introduced the notion of biased arbitraries.

They are multiple approaches to deal with this issue:
- only generate small entries: let's give a try to `jsverify` and you will see that integers will always be small in this case. It means you lose large integer values.
- take into account the run id and increase the size of generated entries as it increases. This approach is the approch of `RapidCheck` in C++, it allows both large and small values to be generated

The idea of `fast-check` was to encourage and not force the creation of small entries in first runs. I wanted to have small and large entries together. Bias is enabled by default. When enabled, for each run the `Arbitrary` will be asked for a biased version of itself with a `freq: number` parameter. It corresponds to the frequency of bias `1 bias for freq generated entries`.

A bias array of `fast-check` generates:
- [1 over freq](https://github.com/dubzzz/fast-check/blob/master/src/check/arbitrary/ArrayArbitrary.ts#L64):
  - [1 over freq](https://github.com/dubzzz/fast-check/blob/master/src/check/arbitrary/ArrayArbitrary.ts#L66): small arrays of bias values
  - [remaining](https://github.com/dubzzz/fast-check/blob/master/src/check/arbitrary/ArrayArbitrary.ts#L67): arrays of bias values
- [remaining](https://github.com/dubzzz/fast-check/blob/master/src/check/arbitrary/ArrayArbitrary.ts#L67): arrays of normal values

**Comment by dubzzz** [comment]
Not sure but there might be a way to have type array just by changing a bit the code of ArrayArbitrary. A specific class is also OK :)

**Comment by dubzzz** [comment]
@bitjson 

I thought again about this question of `uint8array`.. having constraints on their values.

Given current signature for `fc.array` is `fc.array(<constraints for content>, <minLength>, <maxLength>) `, we should maybe come with something close for `uint8array`?

By the way, I believe you tried with the `map` implementation I suggested. Was it working well for your needs? Did you encountered performance issues?

**Comment by dubzzz** [comment]
Still no typed arrays for the moment, but I'm:
1- working on a proper stringified value (in error reports) if someone generates a typed array **#954 (started)**
2- add a signature {min?,max?} on every existing number/array arbitraries **#89 (not started)**
3- we can add them with signatures like: `fc.uint8array({ min: 5, max: 25, minLength: 58 })`...

**Comment by dubzzz** [comment]
@bitjson Closing the issue, the feature will land very shortly into the next minor of fast-check. For the moment I did not included the BigInt variants of typed arrays as they would have implied breaking changes for TypeScript users (it makes compilation fails if nothing is updated on config side for the user).

Before it lands, I'm just wondering: what is the best between `fc.int8array` and `fc.int8Array`? For the moment I adopted the second notation... Any opinion or preference on your side?

**Comment by bitjson** [comment]
(Sorry for the wire silence here.) 

That's great to hear! I'm primarily using `Uint8Array`s since they're a good format for representing values which might otherwise be hex-encoded strings. Looking forward to upgrading!

On capitalization, I would expect the camel-cased variant `int8Array`, so I think that's the right choice 👍

**Comment by dubzzz** [comment]
Great! Release will come soon!

No worry for the silence, actually it took me years to close this issue
